name: Parse List

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.8.0'

      - name: Install dependencies
        run: npm install

      - name: Parse list
        run: node index.js packs

      - name: Print list
        run: cat list.json