name: Pull Request

on:
  pull_request:
    paths:
      - 'packs/**'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    name: Get changed packs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: json
          files: |
            packs/**

      - name: Get changed packs unzip pack.meta and save contents of pack.meta to markdown file
        id: changed-packs
        run: |
          echo ${{ steps.changed-files.outputs.added_modified  }}
          echo "packs=$(echo '${{ steps.changed-files.outputs.added_modified  }}' | jq -r '.[]' | xargs -I {} basename {} .zip | tr '' ',')" >> $GITHUB_OUTPUT

      - name: Unzip packs to extract pack.meta
        run: |
          echo '${{ steps.changed-packs.outputs.packs }}' | jq -r '.[]' | xargs -I {} unzip -o {}.zip -d {}

      - name: Read pack.meta files
        id: read-pack-meta
        run: |
          echo ${{ steps.changed-packs.outputs.packs }}
          echo "packs=$(echo '${{ steps.changed-packs.outputs.packs }}' | jq -r '.[]' | xargs -I {} jq -r '.name' {}/pack.meta | tr '' ',')" >> $GITHUB_OUTPUT

      - name: Write contents of meta to markdown file
        run: |
          echo ${{ steps.read-pack-meta.outputs.packs }}
          echo '${{ steps.read-pack-meta.outputs.packs }}' | jq -r '.[]' | xargs -I {} echo {} >> packs.md

      - name: Log contents of markdown file
        run: |
          cat packs.md

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: packs.md
          reactions: eyes
