name: Pull Request

on:
  pull_request:
    paths:
      - 'packs/**'

jobs:
  build:
    name: Get changed packs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          files: |
            packs/**
          format: json

      - name: Get changed packs
        id: changed-packs
        run: |
          echo "::set-output name=packs::$(echo '${{ steps.changed-files.outputs.all }}' | jq -r '.[]' | grep -o 'packs/[^/]*' | sort -u | tr '' ',')"

      - name: Unzip packs to extract pack.meta
        run: |
          echo '${{ steps.changed-packs.outputs.packs }}' | jq -r '.[]' | xargs -I {} unzip -o {}.zip -d {}

      - name: Read pack.meta files
        id: read-pack-meta
        run: |
          echo "::set-output name=packs::$(echo '${{ steps.changed-packs.outputs.packs }}' | jq -r '.[]' | xargs -I {} jq -r '.name' {}/pack.meta | tr '' ',')"

      - name: Comment meta on PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The following packs have been modified:
            ${{ steps.read-pack-meta.outputs.packs }}
