name: Pull Request

on:
  pull_request:
    paths:
      - 'packs/**'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    name: Get changed packs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: json

      - name: Unzip files from 'packs' directory
        run: |
          mkdir tmp
          # Get all zip files from of each pack and save the name of the pack in packs.md
          echo '## Changed packs:' > packs.md
          echo '' >> packs.md
          echo '```' >> packs.md
          echo '${{ steps.changed-files.outputs.added_modified }}' | jq -r '.[]' | grep 'packs/' | xargs -I {} unzip -o {} -d tmp/{}
          find tmp/ -name 'pack.meta' -exec cat {} \; | jq -r '.name' | tr '' ',' >> packs.md
          echo '```' >> packs.md
          echo '' >> packs.md
          echo '## Changed files:' >> packs.md
          echo '' >> packs.md
          echo '```' >> packs.md
          echo '${{ steps.changed-files.outputs.added_modified }}' >> packs.md
          echo '```' >> packs.md
          echo '' >> packs.md
          echo '## Contents of files:' >> packs.md
          echo '' >> packs.md
          echo '```' >> packs.md
          echo '$(ls -R tmp/)' >> packs.md
          echo '```' >> packs.md

      - name: Log contents of markdown file
        run: |
          cat packs.md

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: packs.md
          reactions: eyes
